---
consul:
  ip: 172.16.2.101
  fqdn: consul.host.test
vault:
  ip: 172.16.2.102
  fqdn: vault.host.test
myapp1:
  ip: 172.16.2.103
  fqdn: myapp1.host.test
myapp2:
  ip: 172.16.2.104
  fqdn: myapp2.host.test
portainer:
  ip: 172.16.2.105
  fqdn: portainer.host.test
